/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GiftIndexRouteImport } from './routes/gift.index'
import { Route as GiftProfileRouteImport } from './routes/gift.profile'
import { Route as GiftSearchRouteImport } from './routes/gift.search'
import { Route as PersonaSlugRouteImport } from './routes/persona.$slug'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorNoticingRouteImport } from './routes/vendor.noticing'
import { Route as VendorPhotosRouteImport } from './routes/vendor.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIndexRoute = GiftIndexRouteImport.update({
  id: '/gift/',
  path: '/gift/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftProfileRoute = GiftProfileRouteImport.update({
  id: '/gift/profile',
  path: '/gift/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftSearchRoute = GiftSearchRouteImport.update({
  id: '/gift/search',
  path: '/gift/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaSlugRoute = PersonaSlugRouteImport.update({
  id: '/persona/$slug',
  path: '/persona/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorNoticingRoute = VendorNoticingRouteImport.update({
  id: '/vendor/noticing',
  path: '/vendor/noticing',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPhotosRoute = VendorPhotosRouteImport.update({
  id: '/vendor/photos',
  path: '/vendor/photos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRoute
  '/meet': typeof MeetRoute
  '/people': typeof PeopleRoute
  '/priorities': typeof PrioritiesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/gift/profile': typeof GiftProfileRoute
  '/gift/search': typeof GiftSearchRoute
  '/persona/$slug': typeof PersonaSlugRoute
  '/vendor/noticing': typeof VendorNoticingRoute
  '/vendor/photos': typeof VendorPhotosRoute
  '/gift/': typeof GiftIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRoute
  '/meet': typeof MeetRoute
  '/people': typeof PeopleRoute
  '/priorities': typeof PrioritiesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/gift/profile': typeof GiftProfileRoute
  '/gift/search': typeof GiftSearchRoute
  '/persona/$slug': typeof PersonaSlugRoute
  '/vendor/noticing': typeof VendorNoticingRoute
  '/vendor/photos': typeof VendorPhotosRoute
  '/gift': typeof GiftIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRoute
  '/meet': typeof MeetRoute
  '/people': typeof PeopleRoute
  '/priorities': typeof PrioritiesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/gift/profile': typeof GiftProfileRoute
  '/gift/search': typeof GiftSearchRoute
  '/persona/$slug': typeof PersonaSlugRoute
  '/vendor/noticing': typeof VendorNoticingRoute
  '/vendor/photos': typeof VendorPhotosRoute
  '/gift/': typeof GiftIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/matches'
    | '/meet'
    | '/people'
    | '/priorities'
    | '/search'
    | '/settings'
    | '/gift/profile'
    | '/gift/search'
    | '/persona/$slug'
    | '/vendor/noticing'
    | '/vendor/photos'
    | '/gift/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/matches'
    | '/meet'
    | '/people'
    | '/priorities'
    | '/search'
    | '/settings'
    | '/gift/profile'
    | '/gift/search'
    | '/persona/$slug'
    | '/vendor/noticing'
    | '/vendor/photos'
    | '/gift'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/matches'
    | '/meet'
    | '/people'
    | '/priorities'
    | '/search'
    | '/settings'
    | '/gift/profile'
    | '/gift/search'
    | '/persona/$slug'
    | '/vendor/noticing'
    | '/vendor/photos'
    | '/gift/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  MatchesRoute: typeof MatchesRoute
  MeetRoute: typeof MeetRoute
  PeopleRoute: typeof PeopleRoute
  PrioritiesRoute: typeof PrioritiesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  GiftProfileRoute: typeof GiftProfileRoute
  GiftSearchRoute: typeof GiftSearchRoute
  PersonaSlugRoute: typeof PersonaSlugRoute
  VendorNoticingRoute: typeof VendorNoticingRoute
  VendorPhotosRoute: typeof VendorPhotosRoute
  GiftIndexRoute: typeof GiftIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/': {
      id: '/gift/'
      path: '/gift'
      fullPath: '/gift/'
      preLoaderRoute: typeof GiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/profile': {
      id: '/gift/profile'
      path: '/gift/profile'
      fullPath: '/gift/profile'
      preLoaderRoute: typeof GiftProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/search': {
      id: '/gift/search'
      path: '/gift/search'
      fullPath: '/gift/search'
      preLoaderRoute: typeof GiftSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$slug': {
      id: '/persona/$slug'
      path: '/persona/$slug'
      fullPath: '/persona/$slug'
      preLoaderRoute: typeof PersonaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/noticing': {
      id: '/vendor/noticing'
      path: '/vendor/noticing'
      fullPath: '/vendor/noticing'
      preLoaderRoute: typeof VendorNoticingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/photos': {
      id: '/vendor/photos'
      path: '/vendor/photos'
      fullPath: '/vendor/photos'
      preLoaderRoute: typeof VendorPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  MatchesRoute: MatchesRoute,
  MeetRoute: MeetRoute,
  PeopleRoute: PeopleRoute,
  PrioritiesRoute: PrioritiesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  GiftProfileRoute: GiftProfileRoute,
  GiftSearchRoute: GiftSearchRoute,
  PersonaSlugRoute: PersonaSlugRoute,
  VendorNoticingRoute: VendorNoticingRoute,
  VendorPhotosRoute: VendorPhotosRoute,
  GiftIndexRoute: GiftIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
